version: '3'

services:
    Tadrosoon:
        image: Tadrosoon/p2p:latest
        build:
            context: .
            dockerfile: Dockerfile
        container_name: Tadrosoon
        hostname: Tadrosoon
        volumes:
            - .env:/src/.env:ro
            - ./app/:/src/app/:ro
            - ./public/:/src/public/:ro
        restart: unless-stopped
        ports:
            - '3000:3000'
# Uncomment below, remove "ports:" section above and configure labels as
# needed for LetsEncrypt TLS certificates with Traefik.
# See https://doc.traefik.io/traefik/user-guides/docker-compose/basic-example/
#   expose:
#     - 3000
#   labels:
#     - "traefik.enable=true"
#     - "traefik.http.routers.Tadrosoon.rule=Host(`Tadrosoon.example.com`)"
#     - "traefik.http.routers.Tadrosoon.entrypoints=websecure"
#     - "traefik.http.routers.Tadrosoon.tls.certresolver=myresolver"
#     - "traefik.http.services.Tadrosoon.loadbalancer.server.port=3000"
